### ISSUE TITLE
unable to run Bayesembler v.1.2.0

### ISSUE THREAD

**Issue by a-dna-n** [bioinformatics-centre/bayesembler#10]
Hello.

I downloaded the 1.2.0 executable from [here](https://github.com/bioinformatics-centre/bayesembler/releases/tag/v1.2.0) but get the following error when I run it:

./bayesembler: error while loading shared libraries: libboost_math_c99.so.1.56.0: cannot open shared object file: No such file or directory

However, I'm able to execute v1.1.1, which I obtained [here](https://github.com/bioinformatics-centre/bayesembler/releases/download/v1.1.1/bayesembler_v1.1.1_linux_x86_64.tar.gz). 

Thanks.

**Comment by lassemaretty** [comment]
Hi, 

Thank you for posting. I have replaced the 1.2.0 binary with a new build that should fix the issue. Please let me know if it works. 

Best,

Lasse

**Comment by a-dna-n** [comment]
Hi, Lasse.

Yes, it works. Thank you.
