### ISSUE TITLE
Feature request: Output file

### ISSUE THREAD

**Issue by marchoeppner** [bioinformatics-centre/bayesembler#4]
Hi,

sorry if this is not the appropriate forum, but it would be useful (or rather necessary, really) to add an 'outfile' option to Bayesembler. As it stands, it will write into the same folder from where it is run and always create a statically named file (assembly.gtf). This makes it somewhat frustrating to use it in pipelines or other complex workflows. 

/Marc

**Comment by colindaven** [comment]
Hi Lasse, I second this request - thanks.
Colin

**Comment by lassemaretty** [comment]
Hi Colin, 

Thank you for posting - we really appreciate the feedback! We will try to push out a minor update containing an output file option next week. Please do not hesitate to post additional feature requests.

Lasse
