### ISSUE TITLE
Feature request: merge GTFs

### ISSUE THREAD

**Issue by colindaven** [bioinformatics-centre/bayesembler#7]
Hi,

it would be nice to have a GTF merging feature similar to Cufflinks merge. However, I was always a little disappointed by Cufflinks merge, and want to be able to merge transcripts from multiple samples more drastically.

For example, I might have 20-40 input GTFs, and want to create a set of High quality (few, 30-50k) or an extended set (100-150k) of transcripts. 

At the moment I have to do this via conversion to fasta format and sequence based clustering, which is time consuming and can give unsatisfactory results.

How do you see this ? Good idea? Too much effort / already provided with tools like PASA, Cufflinks or alternatives ? 

Thanks

**Comment by lassemaretty** [comment]
Hi Colin, 

Thanks again for posting. We are working on a new major release of the *bayesembler* that will be able to do assembly on multiple samples simultaneously such that information can be shared across samples. Furthermore, it will support the use of existing transcript annotations (provided in GTF format) to further improve the assembly as well directly assign annotation labels to the assembly output. We will not put a release date on it yet, but it is currently in the testing phase so it shouldn't be too long.

I hope this answers your question. 

/Lasse
