### ISSUE TITLE
Detect nd data

### ISSUE THREAD

**Issue by colindaven** [bioinformatics-centre/bayesembler#8]
Bayesembler is good on big datasets, but could be optimised further with a simple check if the *nd_minus and *nd_plus bams have been previously created.

Why ? Because it is desirable to run Bayesembler multiple times on the same data to test parameters while avoiding the hefty IO of the initial duplicate removal stage.

This NGS dataset I am dealing with at the moment is multiple samples totalling a BAM of ~160GB.

Thanks a lot, and also for the previous update.

Colin

**Comment by lassemaretty** [comment]
Thank you for letting us know. We actually used to have this feature in the Bayesembler, but we removed it as it had some potentially dangerous side effects - we will look into putting it back in.

Just out of curiosity, what parameters are you optimizing? In case you want to look at different confidence/expected read count thresholds, you could consider running it in `--output-mode full` as is gives you a GTF file (potentially big) with all the transcript candidates (`candidates.gtf`) before filtering on confidence/expected read count. As these values are provided as GTF attributes for the candidates, you should be able to quickly test different threshold values.

Lasse

**Comment by colindaven** [comment]
Hi Lasse,

ok, great, thanks for the tips. That sounds helpful for filtering.

Best wishes,

Colin

**Comment by lassemaretty** [comment]
you're welcome:-)
