### ISSUE TITLE
Feature request: Standardise Bayesembler output to Cufflinks

### ISSUE THREAD

**Issue by colindaven** [bioinformatics-centre/bayesembler#9]
Hi Lasse, 

I have now successfully run Bayesembler on several transcript sets and am trying to get the CDS sequences from the output. Do you have any experience with this ?

In the past I have used a Perl script from the transdecoder 2012 package for this: http://transdecoder.github.io/
Script: cufflinks_gtf_genome_to_cdna_fasta.pl

It did a good job, and I'd like to use it again, yet it only extracts the individual exon sequences or alternatively from the Bayesembler data without combining them into a long multiexon CDS (without introns).

I also saw some differences between the Cufflinks and Bayesembler outputs (see below for two examples, which are not the same transcript)
- No overarching "transcript" feature from Bayesembler - which has also bothered some of my users in the graphical display in JBrowse
- No "exon_number" feature in Bayesembler.

Would it be possible to calculate these ? I believe compatibility with downstream programs and scripts which work with Cufflinks would be a major advantage if easy to implement.

Thanks very much,
Colin

1       Cufflinks       transcript      93387   111087  1000    -       .       gene_id "CUFF.8"; transcript_id "CUFF.8.1"; FPKM "2.3661993829"; frac "0.157337"; conf_lo "1.895853"; conf_h
i "2.833129"; cov "44.134227";
1       Cufflinks       exon    93387   93516   1000    -       .       gene_id "CUFF.8"; transcript_id "CUFF.8.1"; exon_number "1"; FPKM "2.3661993829"; frac "0.157337"; conf_lo "1.895853
"; conf_hi "2.833129"; cov "44.134227";
1       Cufflinks       exon    109510  109675  1000    -       .       gene_id "CUFF.8"; transcript_id "CUFF.8.1"; exon_number "2"; FPKM "2.3661993829"; frac "0.157337"; conf_lo "1.895853
"; conf_hi "2.833129"; cov "44.134227";
1       Cufflinks       exon    109759  109935  1000    -       .       gene_id "CUFF.8"; transcript_id "CUFF.8.1"; exon_number "3"; FPKM "2.3661993829"; frac "0.157337"; conf_lo "1.895853
"; conf_hi "2.833129"; cov "44.134227";
1       Cufflinks       exon    110769  111087  1000    -       .       gene_id "CUFF.8"; transcript_id "CUFF.8.1"; exon_number "4"; FPKM "2.3661993829"; frac "0.157337"; conf_lo "1.895853
"; conf_hi "2.833129"; cov "44.134227";

6       Bayesembler     exon    20387288        20389207        .       +       .       gene_id "graph_118857_plus"; transcript_id "graph_118857_plus_seq0"; transcript_confidence "1"; FPKM
 "38.6952"; FPKM_sd "0.405607"; expected_count "8384.26";
6       Bayesembler     exon    20468756        20470547        .       +       .       gene_id "graph_118857_plus"; transcript_id "graph_118857_plus_seq1"; transcript_confidence "1"; FPKM
 "12.247"; FPKM_sd "0.245679"; expected_count "2444.2";
6       Bayesembler     exon    20532311        20533039        .       +       .       gene_id "graph_118857_plus"; transcript_id "graph_118857_plus_seq3"; transcript_confidence "1"; FPKM
 "11.7757"; FPKM_sd "0.456496"; expected_count "677.976";
6       Bayesembler     exon    20540566        20541604        .       +       .       gene_id "graph_118857_plus"; transcript_id "graph_118857_plus_seq4"; transcript_confidence "1"; FPKM
 "15.0505"; FPKM_sd "0.3873"; expected_count "1489.79";
6       Bayesembler     exon    20555972        20556532        .       +       .       gene_id "graph_118857_plus"; transcript_id "graph_118857_plus_seq5"; transcript_confidence "1"; FPKM
 "12.4851"; FPKM_sd "0.5949"; expected_count "438.632";
6       Bayesembler     exon    20564403        20564704        .       +       .       gene_id "graph_118857_plus"; transcript_id "graph_118857_plus_seq7"; transcript_confidence "1"; FPKM
 "4.82021"; FPKM_sd "1.08253"; expected_count "20.3528";
6       Bayesembler     exon    20571524        20573317        .       +       .       gene_id "graph_118857_plus"; transcript_id "graph_118857_plus_seq8"; transcript_confidence "1"; FPKM
 "6.77399"; FPKM_sd "0.183838"; expected_count "1353.73";
6       Bayesembler     exon    20580763        20582535        .       +       .       gene_id "graph_118857_plus"; transcript_id "graph_118857_plus_seq9"; transcript_confidence "1"; FPKM
 "27.5812"; FPKM_sd "0.360588"; expected_count "5434.54";
6       Bayesembler     exon    20492633        20493290        .       +       .       gene_id "graph_118857_plus"; transcript_id "graph_118857_plus_seq10"; transcript_confidence "1"; FPK
M "6.17059"; FPKM_sd "0.36231"; expected_count "296.741";

**Comment by lassemaretty** [comment]
Hi Colin, 

Thanks for providing us with more suggestions, please keep doing it! We really appreciate the feedback! 

The features you mention should be quite easy to implement in the new release, so expect them within the not too distant future (we stopped using exact release deadlines:-).

Best, 

Lasse

**Comment by colindaven** [comment]
Hi Lasse, 

thanks for this and your positive attitude - let me know if you need some pre-release testing.

cheers,

Colin

**Comment by lassemaretty** [comment]
Thanks. We'll put a pre-release on GitHub as soon as we have it ready!

Best, 

Lasse
